export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAIL = 'UNFOLLOW_FAIL';

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const GET_SINGLE_TWEET_SUCCESS = 'GET_SINGLE_TWEET_SUCCESS';
export const GET_SINGLE_TWEET_FAIL = 'GET_SINGLE_TWEET_FAIL';
export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS';
export const GET_TWEETS_FAIL = 'GET_TWEETS_FAIL';
export const CREATE_TWEET_SUCCESS = 'CREATE_TWEET_SUCCESS';
export const CREATE_TWEET_FAIL = 'CREATE_TWEET_FAIL';
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS';
export const DELETE_TWEET_FAIL = 'DELETE_TWEET_FAIL';
export const LIKE_TWEET_SUCCESS = 'LIKE_TWEET_SUCCESS';
export const LIKE_TWEET_FAIL = 'LIKE_TWEET_FAIL';
export const DELETE_LIKE_TWEET_SUCCESS = 'DELETE_LIKE_TWEET_SUCCESS';
export const DELETE_LIKE_TWEET_FAIL = 'LIKE_TWEET_FAIL';
export const RETWEET_SUCCESS = 'RETWEET_SUCCESS';
export const RETWEET_FAIL = 'RETWEET_FAIL';
export const DELETE_RETWEET_SUCCESS = 'DELETE_RETWEET_SUCCESS';
export const DELETE_RETWEET_FAIL = 'RETWEET_FAIL';

export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const CLOSE_FULL_SCREEN = 'CLOSE_FULL_SCREEN';
